#! /bin/bash
# run a test server on port supplied by argument
# if no argument is supplied, runs on port 8000

if [[ -a pid ]]; then
    pkill -F pid
    value=`cat pid`
    echo "Killed http server running on process with id: $value"
    rm pid
    echo "Deleted file 'pid'"
fi

if [ $# -eq 0 ]
then
    echo "No port supplied, using port 8000"
    python3.8 -m http.server 8000 --directory static &> /dev/null & echo $! > pid &
    pid_val=`cat pid`
    echo "Started server on port 8000. pid: $pid_val"
else
    python3.8 -m http.server $1 --directory static &> /dev/null & echo $! > pid &
    pid_val=`cat pid`
    echo "Started server on port $1. pid: $pid_val"
fi

return 0
